<a href="https://colab.research.google.com/github/PosgradoMNA/actividades-del-projecto-equipo-2/blob/main/Semana4_actividad1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**ACTIVIDAD SEMANAL -- 4**

* **Equipo:** 2
* **Integrantes:** Andrea Carolina Treviño Garza (A01034993),
Mario Alberto Corona Cadenas (A01793016)

###**Parte 1: Ejercicio guiado** : Revise el ejercicio guiado para el análisis de componentes principales utilizando el conjunto de datos

Paso 1: Determine el número mínimo de componentes principales que representan la mayor parte de la variación en sus datos
* Utilice la proporción acumulada de la varianza que explican los componentes para determinar la cantidad de varianza que explican los componentes principales

In [40]:
#Importamos liberías principales:
import pandas as pd
import numpy as np

In [41]:
#Leemos la base de datos con libería pandas(pd) y guardamos el dataframe en la variable df.
df = pd.read_csv("https://raw.githubusercontent.com/PosgradoMNA/Actividades_Aprendizaje-/main/default%20of%20credit%20card%20clients.csv", index_col = 0)
df.index.name = None
df.head()

,X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,...,X15,X16,X17,X18,X19,X20,X21,X22,X23,Y
1,20000,2.0,2.0,1.0,24.0,2.0,2.0,-1.0,-1.0,-2.0,...,0.0,0.0,0.0,0.0,689.0,0.0,0.0,0.0,0.0,1.0
2,120000,2.0,2.0,2.0,26.0,-1.0,2.0,0.0,0.0,0.0,...,3272.0,3455.0,3261.0,0.0,1000.0,1000.0,1000.0,0.0,2000.0,1.0
3,90000,2.0,2.0,2.0,34.0,0.0,0.0,0.0,0.0,0.0,...,14331.0,14948.0,15549.0,1518.0,1500.0,1000.0,1000.0,1000.0,5000.0,0.0
4,50000,2.0,2.0,1.0,37.0,0.0,0.0,0.0,0.0,0.0,...,28314.0,28959.0,29547.0,2000.0,2019.0,1200.0,1100.0,1069.0,1000.0,0.0
5,50000,1.0,2.0,1.0,57.0,-1.0,0.0,-1.0,0.0,0.0,...,20940.0,19146.0,19131.0,2000.0,36681.0,10000.0,9000.0,689.0,679.0,0.0

In [42]:
#Revisamos el método info para verificar que tipo de datos tiene cada columna.
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 30000 entries, 1 to 30000
Data columns (total 24 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   X1      30000 non-null  int64
 1   X2      29999 non-null  float64
 2   X3      29998 non-null  float64
 3   X4      29998 non-null  float64
 4   X5      29995 non-null  float64
 5   X6      29997 non-null  float64
 6   X7      29995 non-null  float64
 7   X8      29993 non-null  float64
 8   X9      29991 non-null  float64
 9   X10     29984 non-null  float64
 10  X11     29986 non-null  float64
 11  X12     29989 non-null  float64
 12  X13     29989 non-null  float64
 13  X14     29987 non-null  float64
 14  X15     29985 non-null  float64
 15  X16     29983 non-null  float64
 16  X17     29990 non-null  float64
 17  X18     29992 non-null  float64
 18  X19     29991 non-null  float64
 19  X20     29992 non-null  float64
 20  X21     29989 non-null  float64
 21  X22     29989 non-null  float64
 22  X23     29995 non-null  float64
 23  Y       29997 non-null  float64
dtypes: float64(23), int64(1)
memory usage: 5.7 MB

In [43]:
#Copiamos nuestro dataframe original en otra variable para no perder datos originales
my_df = df.copy()

In [44]:
# Reemplazamos los valosres vacíos con la mediana de cada columna.
for column in my_df:
  current_media = my_df[column].median()
  my_df[column].fillna(value = current_media, inplace = True)

#Revisamos que efectivamente no quede ningún valor vacío.
my_df.isnull().any()

X1     False
X2     False
X3     False
X4     False
X5     False
X6     False
X7     False
X8     False
X9     False
X10    False
X11    False
X12    False
X13    False
X14    False
X15    False
X16    False
X17    False
X18    False
X19    False
X20    False
X21    False
X22    False
X23    False
Y      False
dtype: bool

In [45]:
#Importar librería de sklearn para realizar Estandarización de datos.
from sklearn import preprocessing

scaler = preprocessing.StandardScaler().fit(my_df)
Norm_df = scaler.transform(my_df)
Norm_df = pd.DataFrame(Norm_df)

columns = ["X"+str(i) for i in range(0,24)]
Norm_df.columns = columns

In [46]:
#Inspeccionamos resultados de Estandarización, que media sea cercana a 0 y desviación cercana a 1. 
Norm_df_info = {"Mean":Norm_df[Norm_df.columns].mean()[0:24], "Standard Deviation":Norm_df[Norm_df.columns].std()[0:24]}

pd.DataFrame(Norm_df_info, index = Norm_df.columns).transpose()

,X0,X1,X2,X3,X4,X5,X6,X7,X8,X9,...,X14,X15,X16,X17,X18,X19,X20,X21,X22,X23
Mean,-6.063298e-17,2.823223e-16,6.252776e-17,-6.063298e-17,-7.579123e-17,-5.115908e-17,-3.694822e-17,-6.631732e-18,3.126388e-17,-5.873820e-17,...,-3.221127e-17,-5.115908e-17,-2.984279e-17,-1.231607e-17,-9.473903e-19,9.473903e-18,1.563194e-17,8.526513e-18,2.332949e-17,-8.289665e-17
Standard Deviation,1.000017e+00,1.000017e+00,1.000017e+00,1.000017e+00,1.000017e+00,1.000017e+00,1.000017e+00,1.000017e+00,1.000017e+00,1.000017e+00,...,1.000017e+00,1.000017e+00,1.000017e+00,1.000017e+00,1.000017e+00,1.000017e+00,1.000017e+00,1.000017e+00,1.000017e+00,1.000017e+00

In [48]:
#Aplicamos PCA
from sklearn.decomposition import PCA

pca = PCA(n_components= 24)
pca_t = pca.fit_transform(Norm_df)
pca_t

array([[-1.80129502e+00, -1.26999245e+00, -5.89794964e-01, ...,
         1.60111331e-02,  1.59703847e-02,  1.05354427e-02],
       [-6.71989169e-01, -2.40624499e+00,  1.04078800e+00, ...,
         3.49362464e-03,  3.22698112e-03,  6.44021437e-03],
       [-8.58796766e-01, -9.69714915e-01,  4.70518908e-01, ...,
        -7.86535493e-02, -4.08121356e-02, -5.65105913e-02],
       ...,
       [ 4.65644612e-01, -3.61037034e+00,  5.01117938e-01, ...,
         1.53629392e-02, -1.27648086e-02, -2.10044001e-02],
       [ 7.19101461e-01,  3.83699825e-01,  3.25141107e-01, ...,
         1.77293575e-01, -1.43822913e-01, -9.28236208e-03],
       [-6.27033899e-02, -1.13603689e+00, -1.44484650e+00, ...,
        -2.19443995e-02,  1.14647790e-01, -4.84383341e-02]])

In [66]:
# Obtenemos un resumen del PCA 
PCAcolumns = ["PC"+str(i) for i in range(1,25)]

pcaSummary = pd.DataFrame({'Standard deviation': np.sqrt(pca.explained_variance_.round(4)),
                          'Proportion of variance': pca.explained_variance_ratio_.round(4),
                          'Cumulative proportion': np.cumsum(pca.explained_variance_ratio_.round(4))#column 
                          }
                          ).transpose()

pcaSummary.columns = PCAcolumns
pcaSummary

,PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,PC10,...,PC15,PC16,PC17,PC18,PC19,PC20,PC21,PC22,PC23,PC24
Standard deviation,2.55959,2.049707,1.246234,1.214578,1.020049,0.987117,0.957236,0.952365,0.941382,0.933435,...,0.724155,0.630872,0.509411,0.498899,0.434626,0.36318,0.264953,0.20199,0.15906,0.152315
Proportion of variance,0.27300,0.175000,0.064700,0.061500,0.043400,0.040600,0.038200,0.037800,0.036900,0.036300,...,0.021900,0.016600,0.010800,0.010400,0.007900,0.00550,0.002900,0.00170,0.00110,0.001000
Cumulative proportion,0.27300,0.448000,0.512700,0.574200,0.617600,0.658200,0.696400,0.734200,0.771100,0.807400,...,0.942300,0.958900,0.969700,0.980100,0.988000,0.99350,0.996400,0.99810,0.99920,1.000200

In [72]:
#Definimos un límite dinámico para decidir cuantos Componentes del PCA consideramos.
threshold = 0.85
PC_count = 1
for pc in pcaSummary.transpose()["Cumulative proportion"]:
  if pc >= threshold: 
    print("PC",PC_count)
    break
  PC_count = PC_count + 1

PC 12

In [73]:
#Aquí observamos la composición de cada componente del PCA en términos de nuestras variables originales (seleccionamos los de nuesto límite dinámico PC_count)

CompVar_df = pd.DataFrame(
                        pca.components_.round(4),
                        columns = pcaSummary.columns, 
                        index = Norm_df.columns) 
CompVar_df.iloc[:,:PC_count]

,PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,PC10,PC11,PC12
X0,0.0657,-0.0221,0.0199,-0.0056,0.0140,0.1645,0.1972,0.2032,0.2099,0.2135,0.2088,0.3328
X1,0.3116,0.0308,-0.0885,-0.0397,0.0627,-0.2967,-0.3281,-0.3349,-0.3345,-0.3213,-0.2959,0.1434
X2,0.0100,0.0278,-0.3172,0.4670,-0.4771,-0.0207,0.0188,0.0638,0.0920,0.1120,0.1141,-0.1462
X3,0.0770,-0.0793,0.2271,-0.4300,0.4480,0.0201,0.0478,0.0798,0.1037,0.1101,0.1047,-0.1717
X4,-0.1983,0.7378,0.4515,-0.0264,-0.1391,-0.1119,-0.0518,-0.0023,0.0379,0.0553,0.0635,-0.0149
X5,-0.2654,-0.6272,0.3888,0.2307,0.0053,-0.1358,-0.0620,-0.0167,0.0072,0.0186,0.0108,0.0118
X6,-0.2632,0.0058,0.4116,0.1901,-0.1401,0.2177,0.0431,-0.0888,-0.1962,-0.2348,-0.2333,0.0298
X7,0.0458,0.0747,-0.3156,-0.1199,0.0484,-0.0250,-0.0800,-0.0453,-0.0135,0.0429,0.0816,-0.0605
X8,-0.0269,-0.0473,0.0549,0.0108,0.0070,-0.0356,0.0053,-0.0079,-0.0147,0.0133,0.0930,-0.0242
X9,0.0223,0.0180,-0.1551,-0.0562,0.0473,-0.0325,-0.0338,-0.0111,0.0455,0.0560,0.0010,-0.0648
X10,0.0198,0.0216,0.0644,0.0393,0.0097,-0.0106,0.0009,-0.0239,-0.0506,0.0753,0.0233,0.0108
X11,0.0160,-0.0161,0.0131,-0.0038,-0.0171,-0.0057,0.0030,-0.1096,0.0124,0.0404,0.0559,0.0074
X12,-0.1258,0.0071,-0.1949,-0.2284,-0.0908,0.5107,0.3982,0.1524,-0.1521,-0.3041,-0.3520,0.0518
X13,0.3492,0.1755,0.0649,0.6448,0.5718,0.1996,0.1307,0.0783,0.0083,-0.0533,-0.0773,-0.0008
X14,-0.7540,0.1135,-0.3737,0.1338,0.4336,-0.0968,-0.0801,-0.0823,-0.0604,-0.0220,0.0378,0.0140
X15,-0.0194,0.0239,-0.0245,0.0094,0.0142,-0.6399,0.2856,0.5296,0.1756,-0.1672,-0.3502,0.0664
X16,0.0437,-0.0003,0.0118,0.0076,0.0004,-0.2512,0.5574,-0.0990,-0.5869,-0.0822,0.4992,0.0338
X17,-0.0233,0.0216,-0.0392,-0.0133,-0.0005,-0.0011,-0.0567,-0.1580,0.0616,0.1424,0.0655,0.5503
X18,0.0062,-0.0039,0.0041,-0.0058,-0.0054,0.1374,-0.4867,0.6064,-0.2274,-0.3831,0.3949,0.0504
X19,0.0068,-0.0019,0.0023,-0.0006,-0.0058,-0.0340,0.1386,-0.3040,0.5670,-0.6757,0.3192,0.0128
X20,-0.0098,0.0019,-0.0026,-0.0024,-0.0002,-0.0061,-0.0313,0.0251,0.0193,0.0272,-0.0434,0.4149
X21,0.0144,-0.0007,0.0005,-0.0003,-0.0015,0.0007,0.0128,-0.0277,0.0017,0.0235,-0.0127,-0.4325
X22,-0.0006,-0.0008,0.0014,0.0007,0.0001,-0.0027,0.0033,-0.0085,0.0141,-0.0083,0.0003,-0.1834
X23,0.0027,0.0008,0.0017,-0.0012,0.0003,0.0006,0.0000,-0.0048,-0.0014,-0.0006,0.0046,-0.3182

In [75]:
#

CompVar_df.iloc[:,:PC_count].idxmax()

PC1     X13
PC2      X4
PC3      X4
PC4     X13
PC5     X13
PC6     X12
PC7     X16
PC8     X18
PC9     X19
PC10     X0
PC11    X16
PC12    X17
dtype: object

pcsSummary = pd.DataFrame({'Standard deviation': np.sqrt(pcs.explained_variance_),
                          'Proportion of variance': pcs.explained_variance_ratio_,
                          'Cumulative proportion': np.cumsum(pcs.explained_variance_ratio_)#column 
                          }
                          )

Paso 2: Interprete cada componente principal en términos de las variables originales
* Examine la magnitud y la dirección de los coeficientes de las variables originales.
*Nota: Cuanto mayor sea el valor absoluto del coeficiente, más importante será la variable correspondiente en el cálculo del componente.*

Paso 3: Identifique valores atípicos.
* Realice alguna gráfica de valores atípicos o boxplot para identificar los valores atípicos. Cualquier punto que esté más alejado de la línea de referencia es un valor atípico.

###**Parte 2:** Responde las siguientes preguntas en una celda de texto en Jupyter Notebook

1.   ¿Cuál es el número de componentes mínimo y por qué?

2.   ¿Cuál es la variación de los datos que representan esos componentes?

3.   ¿Cuál es la pérdida de información después de realizar PCA?

4.   De las variables originales, ¿Cuál tiene mayor y cuál tiene menor importancia en los componentes principales?

5.   ¿Cuándo se recomienda realizar un PCA y qué beneficios ofrece para Machine Learning?